#ifndef CONSTANTS
#define CONSTANTS

#define MAP_HEIGHT 21
#define MAP_WIDTH 21

#define CELL_SIZE 16

#define POINTS_FOR_PELLET 25
#define LONG_SCATTER_DURATION 512
#define SHORT_SCATTER_DURATION 256
#define CHASE_DURATION 1024

#endif // CONSTANTS

