#ifndef CONSTANTS
#define CONSTANTS

#define MAP_HEIGHT 21
#define MAP_WIDTH 21

#define CELL_SIZE 16

#define POINTS_FOR_PELLET 25
#define LONG_SCATTER_DURATION 512
#define SHORT_SCATTER_DURATION 256
#define CHASE_DURATION 1024

#define PACMAN_SPEED 2

#define PACMAN_ANIMATION_FRAMES 6
#define PACMAN_ANIMATION_SPEED 4
#define PACMAN_DEATH_FRAMES 12
#define PACMAN_SPEED 2
#define ENERGIZER_DURATION 512

#endif // CONSTANTS

