#ifndef CONSTANTS
#define CONSTANTS

#define CELL_SIZE 16
#define FONT_HEIGHT 16

#define GHOST_1_CHASE 2
#define GHOST_2_CHASE 1
#define GHOST_3_CHASE 4

#define TOTAL_GHOSTS 4
#define GHOST_ANIMATION_FRAMES 6
#define GHOST_ANIMATION_SPEED 4
#define GHOST_ESCAPE_SPEED 4
#define GHOST_FRIGHTENED_SPEED 3
#define GHOST_SPEED 1

#define MAP_HEIGHT 21
#define MAP_WIDTH 21

#define PACMAN_ANIMATION_FRAMES 6
#define PACMAN_ANIMATION_SPEED 4
#define PACMAN_DEATH_FRAMES 12
#define PACMAN_SPEED 2

#define SCREEN_RESIZE 2

#define CHASE_DURATION 1024
#define ENERGIZER_DURATION 512
#define FRAME_DURATION 16667
#define GHOST_FLASH_START 64
#define LONG_SCATTER_DURATION 512
#define SHORT_SCATTER_DURATION 256

#define POINTS_FOR_PELLET 25
#define POINTS_FOR_GHOST 200

#define BOMB_ANIMATION_FRAMES 2
#define BOMB_ANIMATION_SPEED 4
#define BOMB_BOOM_FRAME 3
#define BOMB_DROP_INTERVAL 256
#define BOMB_MAX_LIFETIME 128

#endif // CONSTANTS

